### ISSUE TITLE
Services Page

### ISSUE THREAD

**Issue by nirajgiriXD** [ChandraByte/hamro-nepse#16]
## Description

- Create our services / features page
- Make the services available in grid structure
- Make the cards clickable

---

## Reference

- Initial design: https://github.com/ChandraByte/nsa/discussions/2#discussion-6011242
- Use grid structure of this: https://codepen.io/knyttneve/pen/ZEbQepZ

**Comment by Sandesh-Ghimire** [comment]
This will be available soon.

**Comment by Sandesh-Ghimire** [comment]
![image](https://github.com/ChandraByte/hamro-nepse/assets/62834029/ccf42fba-ac5d-43fd-8e25-8d7fa1e29542)
 will this be fine? or do you want some changes?

**Comment by nirajgiriXD** [comment]
> will this be fine? or do you want some changes?

LGTM

**Comment by nirajgiriXD** [comment]
@Sandesh-Ghimire Please implement the dark mode version for `service page`. Reference can be taken from the `landing page`.

**Comment by Sandesh-Ghimire** [comment]
Can you provide the file name of landing page? i checked by running the code but i don't see any dark mode in any page as far as i have updated from repo.

**Comment by Sandesh-Ghimire** [comment]
![image](https://github.com/ChandraByte/hamro-nepse/assets/62834029/84699a55-1547-422d-b2e9-f30e6a02d335)
here is the view, guide me here.

**Comment by nirajgiriXD** [comment]
@Sandesh-Ghimire Your system (os) theme is set to `light mode / theme`, change it to `dark mode / theme` in order to see the dark mode version of the landing page.

**Comment by Sandesh-Ghimire** [comment]
@nirajgiriXD  i would like to see the code of it. could you give me the file name where it is implemented?

**Comment by nirajgiriXD** [comment]
@Sandesh-Ghimire There is no specific code for dark mode implementation, it's achieved through the use of `Tailwind CSS` in html component.

Code example:
```HTML
<hr className="my-6 border-gray-200 sm:mx-auto dark:border-gray-400 dark:border-white lg:my-8" />
```

Here the classes `dark:border-gray-400` and `dark:border-white` (class having `dark:` prefix) will be used instead of regular class if the user preference is set to dark theme/appearance/mode else the regular class will be used in case of light theme/appearance/mode.

**Comment by nirajgiriXD** [comment]
Closing the issue as the services page is complete.
