### ISSUE TITLE
Research: Table package suitable for the Project

### ISSUE THREAD

**Issue by nirajgiriXD** [ChandraByte/hamro-nepse#31]
## Description

The project will be using the tables extensively, so there should be a common table react package that will be used throughout the project for any table requirement.

---

## Expectation

The table should be following features:

- [ ] Sorting
- [ ] Filtering
- [ ] Resizable (optional)
- [ ] Headless (optional)

**Comment by sumanjha108155** [comment]
After a extensive research for the tables library that should be used extensively throughout the project , I found these below library to be much helpfull as they match the scenario and use case of the project. They also provide extensive documentation support with large communtiy using them. Below are some links to refer to them (with examples). 

1. [Material React Table](https://www.material-react-table.com/docs/examples)
2. [AG Grid](https://www.ag-grid.com/react-data-grid/getting-started/)
3. [AG Grid populate table with API call demo](https://www.youtube.com/watch?v=lQ8HwF9cwvs)
4. [Material UI](https://mui.com/material-ui/react-table/)
5. [Material UI populate table with API call demo](https://www.youtube.com/watch?v=S_mgSHCWCmA)

**Comment by nirajgiriXD** [comment]
@sumanjha108155 The tables libraries you shared do have the features that we were looking for. Please feel free to proceed with the table implementation by using either [Material React Table](https://www.material-react-table.com/docs/examples) or [AG Grid](https://www.ag-grid.com/react-data-grid/getting-started/).

**Comment by sumanjha108155** [comment]
@nirajgiriXD Sure , thanks for the acknowledgement.

**Comment by nirajgiriXD** [comment]
Closing the issue as `material-react-table` has been selected for the project.
