### ISSUE TITLE
Fix navbar items

### ISSUE THREAD

**Issue by nirajgiriXD** [ChandraByte/hamro-nepse#87]
## Description

The navbar items have following issues:

- Navitems are not vertically aligned to center
- Navitems height are inconsistent

**Comment by sumanjha108155** [comment]
@nirajgiriXD can you please explain the inconsistency of the height?

**Comment by nirajgiriXD** [comment]
@sumanjha108155 

- The search box's height is not equal to the logo height.

![image](https://github.com/ChandraByte/hamro-nepse/assets/51747980/34625348-c106-4303-a2a6-bb8de2fffb40)
